name: Notificaci贸n Push Main - DevOps ITLA

on:
  push:
    branches: [ main ]

jobs:
  deploy-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout del c贸digo
        uses: actions/checkout@v4

      - name:  Ejecutar Hola Mundo
        run: node index.js

      - name:  Enviar notificaci贸n a ntfy.sh
        run: |
          curl -X POST \
            -H "Title: Despliegue Exitoso " \
            -H "Tags: rocket,tada" \
            -d "隆Hola Mundo desplegado con 茅xito!

Repositorio: ${{ github.repository }}
Usuario: ${{ github.actor }}
Rama: main

隆Integraci贸n Continua activada correctamente! " \
            https://ntfy.sh/devops-itla
